#!/bin/bash
set -e

echo "=== DOCKER ENTRYPOINT ULTIMATE ==="
echo "Arreglando estructura completa de imports..."

cd /app

# 1. HACER QUE /app SEA UN PAQUETE PYTHON VÁLIDO
# Crear __init__.py en todos los directorios necesarios
for dir in /app /app/api /app/api/routers /app/api/schemas /app/database /app/services /app/core; do
    if [ -d "$dir" ] && [ ! -f "$dir/__init__.py" ]; then
        echo "Creando $dir/__init__.py"
        echo "# Auto-generated by entrypoint" > "$dir/__init__.py"
    fi
done

# 2. ARREGLAR TODOS LOS IMPORTS EN TODOS LOS ARCHIVOS
echo ""
echo "=== Arreglando imports en TODOS los archivos ==="

# Lista de archivos a arreglar
FILES_TO_FIX="
api/dependencies.py
api/routers/shipment.py
api/routers/seller.py
"

for file in $FILES_TO_FIX; do
    if [ -f "$file" ]; then
        echo "Arreglando $file..."
        # Hacer backup
        cp "$file" "${file}.backup"
        # Reemplazar imports relativos
        sed -i 's|from \.\.database|from database|g' "$file"
        sed -i 's|from \.\.services|from services|g' "$file"
        sed -i 's|from \.\.dependencies|from api.dependencies|g' "$file"
        sed -i 's|from \.\.schemas|from api.schemas|g' "$file"
        sed -i 's|from \.\.|from api.|g' "$file"
    fi
done

# 3. MOSTRAR LOS CAMBIOS
echo ""
echo "=== Cambios realizados ==="
echo "api/dependencies.py (líneas 5-10):"
sed -n '5,10p' api/dependencies.py
echo ""
echo "api/routers/shipment.py (líneas 1-10):"
sed -n '1,10p' api/routers/shipment.py

# 4. CONFIGURAR PYTHONPATH
export PYTHONPATH=/app:$PYTHONPATH
echo ""
echo "PYTHONPATH: $PYTHONPATH"
echo ""

# 5. PROBAR IMPORTS COMPLETAMENTE
echo "=== Prueba FINAL de imports ==="
python3 -c "
import sys
import os

print('Directorio actual:', os.getcwd())
print('sys.path:', sys.path[:3])

# Probar import crítico
test_imports = [
    ('database.session', 'from database.session import get_session'),
    ('services.seller', 'from services.seller import SellerService'),
    ('services.shipment', 'from services.shipment import ShipmentService'),
    ('api.dependencies', 'from api.dependencies import SellerServiceDep, ShipmentServiceDep'),
    ('main', 'from main import app'),
]

all_ok = True
for name, import_stmt in test_imports:
    try:
        exec(import_stmt)
        print(f'✅ {name}')
    except Exception as e:
        print(f'❌ {name}: {e}')
        all_ok = False

if all_ok:
    print('\\n🎉 ¡TODOS LOS IMPORTS FUNCIONAN!')
    print('🎉 ¡API LISTA PARA INICIAR!')
else:
    print('\\n❌ Algunos imports fallaron')
    sys.exit(1)
"

# 6. INICIAR API
echo ""
echo "=== INICIANDO FASTAPI ==="
echo "Servidor en: http://0.0.0.0:8000"
echo "Docs en: http://localhost:8000/docs"
echo ""
exec uvicorn main:app --host 0.0.0.0 --port 8000
